import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'Biel' at '3/8/16 12:46 PM' with Gradle 2.11
 *
 * @author Biel, @date 3/8/16 12:46 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("someMethod should return 'true'", true);
    }
}
